23-css/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/photo_gallery', to: 'pages#photo_gallery'
  get '/grand_canyon', to: 'pages#grand_canyon'
end

23-css/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

23-css/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        
    end

    def grand_canyon

    end

    def photo_gallery

    end
end

23-css/app/helpers/application_helper.rb
module ApplicationHelper
end

23-css/app/helpers/pages_helper.rb
module PagesHelper
end

23-css/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NationalPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Fira+Sans:400,700&display=swap" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

23-css/app/views/pages/grand_canyon.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>US National Parks - Grand Canyon</title>
  
  </head>
  <body>
    <div>
        <a href="/">Home</a>
        <a href="/photo_gallery">Image Gallery</a></li>
    </div>

    <h1>Grand Canyon</h1>

      <div class="wrapper">

      <div class='grand-canyon-image'>
        <!-- Show the javascript way -->
        <%= image_tag("grand_canyon.jpg") %>
      </div>


      <div class="article-body">
        <p>Volunteering your time; it pays you and your whole community fantastic dividends. Just think about these things in your mind - then bring them into your world. Just make little strokes like that. I guess that would be considered a UFO. A big cotton ball in the sky. We want to use a lot pressure while using no pressure at all.</p>

        <p>That's a crooked tree. We'll send him to Washington. Don't be bashful drop me a line. That is when you can experience true joy, when you have no fear. Let your heart take you to wherever you want to be. A tree needs to be your friend if you're going to paint him.</p>

        <p>It's beautiful - and we haven't even done anything to it yet. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. These things happen automatically. All you have to do is just let them happen. For the lack of a better word I call them hangy downs.</p>
      </div>

      <div class='park-info'>
        <h3>Park Information</h3>
        <p>Open: sunrise to sunset</p>
        <p>Admission: $25.00 </p>
      </div>
   
       </div> <!--/wrapper -->

  </body>
</html>

23-css/app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>National Parks</title>

  
  </head>

  <style>
  

  </style>

  <body>
      <div id="newbar" class="ui inverted menu">
          <a class="item" href="/">Home</a>
          <!-- <a href="/photo_gallery">Image Gallery</a></li> -->
          <%= link_to "Image Gallery", photo_gallery_path, class: "item" %>
          <i id="american_sign" class="american sign language interpreting icon"></i>
      </div>


   
    <!-- apply header -->
    <!-- apply id -->
    <div class="header">
      <h1 id="home-page-title"> US National Parks </h1>
    </div>

    <!-- apply box model -->
    <div class="intro">
      <p>The United States has 60 protected areas known as national parks that are operated by the National Park Service, an agency of the Department of the Interior. National parks must be established by an act of the United States Congress. Criteria for the selection of national parks include natural beauty, unique geological features, unusual ecosystems, and recreational opportunities (though these criteria are not always considered together).</p>
    </div>

    <div>
      <h2>Featured Park: The Grand Canyon</h2>
      <button class="btn"><%= link_to "Visit the Grand Canyon", grand_canyon_path %></button>
    </div>

    <div>
      <p>Thanks for visiting the parks page!</p>
    </div>
  </body>
</html>

23-css/app/views/pages/photo_gallery.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>US National Parks - Image Gallery</title>

  </head>
  <body>
    <div>
        <a href="/">Home</a>
        <a href="/photo_gallery">Image Gallery</a></li>
    </div>

    <h1>Image Gallery</h1>
    <div class="image-gallery">
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img") %>
        <%= image_tag("redwood_forest.jpg" , class: "gallery-img") %>
        <%= image_tag("bison.jpg", class: "gallery-img") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img") %>
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img") %>
        <%= image_tag("bison.jpg", class: "gallery-img") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img") %>
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img") %>
        <%= image_tag("bison.jpg", class: "gallery-img") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img") %>
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img") %>
        <%= image_tag("bison.jpg", class: "gallery-img") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img") %>
    </div>
  </body>
</html>