22-authorization/snack-tracker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "snacks#home", as: "home"
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#process_login"
  get "/logout", to: "sessions#logout"
  resources :snacks
  resources :retailers, except: [:destroy]
  resources :users, only: [:new, :create]
end

22-authorization/snack-tracker/app/models/retailer.rb
class Retailer < ApplicationRecord
    has_many :snacks
    accepts_nested_attributes_for :snacks, reject_if: 
        Proc.new {|attributes| attributes[:name].blank?}

    validates :name, presence: true, 
        uniqueness: {case_sensitive: false}
    validates :year_established, presence: true
    validate :year_established_must_be_valid,
        unless: Proc.new {|attr| attr.year_established.blank?}
    
    def year_established_must_be_valid
        if !(self.year_established >= 1800 && 
            self.year_established <= Date.today.year)
            errors.add(:year_established, "must be between 1800 & #{Date.today.year}")
        end
    end
end

22-authorization/snack-tracker/app/models/snack.rb
class Snack < ApplicationRecord

    belongs_to :retailer
    validates :name, presence: true, 
        uniqueness: { case_sensitive: false }
    validates :calories, presence: true
    validates_numericality_of :calories
    validates :deliciousness, presence: true

    def yumminess

        if is_yummy?
            return  "this is a yummy snack"
        else 
            return "this is not yummy"
        end
    end

    private

    def is_yummy?
        return self.deliciousness > 7
    end
end

22-authorization/snack-tracker/app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    validates :username, uniqueness: {case_sensitive: false}

    def display_name
        return self.username.capitalize
    end

    
end

22-authorization/snack-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

    def authorized
        if !logged_in?
            redirect_to login_path, 
                notice: "You must be logged in to see that page"
        end
    end

    
end

22-authorization/snack-tracker/app/controllers/retailers_controller.rb
class RetailersController < ApplicationController

  before_action :authorized
  
  def index
    @retailers = Retailer.all
  end

  def show
    @retailer = Retailer.find(params[:id])
  end

  def new
    @retailer = Retailer.new
    @retailer.snacks.build
  end

  def create
    @retailer = Retailer.new(retailer_params)
    if @retailer.valid?
      @retailer.save
      redirect_to retailer_path(@retailer)
    else
      @retailer.snacks.build
      render :new
    end
  end

  def edit
    @retailer = Retailer.find(params[:id])
  end

  def update
    @retailer = Retailer.find(params[:id])
    @retailer.update(retailer_params)
    redirect_to retailer_path(@retailer)
  end

  private

  def retailer_params
    params.require(:retailer).permit(:name, :year_established,
        snacks_attributes: [:name, :calories, :deliciousness])
  end

end

22-authorization/snack-tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
  end

  def process_login
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to snacks_path
    else
        flash.now["notice"] = "No user found with that name and password"
        render :login
    end

  end

  def logout
    session.clear
    redirect_to login_path
  end


end

22-authorization/snack-tracker/app/controllers/snacks_controller.rb
class SnacksController < ApplicationController

    before_action :find_snack, only: [:show, :edit, :update]
    before_action :authorized
    
    def home
    end

    def index
        @snacks = Snack.all
    end

    def show
        cookies["my_favorite"] = "chocolate chip"
        session["secret_favorite"] = "oatmeal raisin"
        cookies["last_visited"] = @snack.name
    end

    def new
        @snack = Snack.new
        render :new
    end

    def create
        @snack = Snack.new(snack_params)
        if @snack.valid?
            @snack.save
            redirect_to snack_path(@snack)
        else
            render :new
        end
    end

    def edit
        # test
    end

    def update
        @snack.update(snack_params)
        redirect_to snack_path(@snack)
    end

    def destroy
        Snack.destroy(params[:id])
        redirect_to snacks_path
    end

    private

    def find_snack
        @snack = Snack.find(params[:id])
    end

    def snack_params
        params.require(:snack).permit(:name, 
            :calories, :deliciousness, :retailer_id)
    end
end

22-authorization/snack-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to snacks_path, 
            notice: "#{@user.username} created successfully"
    else
        render :new
    end
  end

  private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

22-authorization/snack-tracker/app/helpers/retailers_helper.rb
module RetailersHelper
end

22-authorization/snack-tracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

22-authorization/snack-tracker/app/helpers/snacks_helper.rb
module SnacksHelper
end

22-authorization/snack-tracker/app/helpers/users_helper.rb
module UsersHelper
end

22-authorization/snack-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snacktracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <% if current_user %>
          <div class="left">Welcome <%= current_user.display_name %></div>
          <div class="right"><%= link_to "Logout", logout_path %></div>
      <% else %>
          <%= link_to "Login", login_path %>
      <% end %>
    </div>

    <% if notice %>
      <div class="notice"><%= notice %></div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

22-authorization/snack-tracker/app/views/retailers/edit.html.erb
<h1>Edit this retailer</h1>

<%= form_for @retailer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

22-authorization/snack-tracker/app/views/retailers/index.html.erb
<h1>Retailers#index</h1>

<ul>
    <% @retailers.each do |retailer| %>
        <li><%= link_to retailer.name, retailer_path(retailer) %></li>
    <% end %>
</ul>

22-authorization/snack-tracker/app/views/retailers/new.html.erb
<h1>Create a new retailer</h1>

<%= render partial: "shared/error_list", locals: {new_thing: @retailer} %>

<%= form_for @retailer do |f| %>
    <%= f.label :name, "Retailer name" %>
    <%= f.text_field :name %>
    <%= f.label :year_established %>
    <%= f.number_field :year_established %>


    <h4>Snacks</h4>
        <%= f.fields_for :snacks do |snack| %>
            <%= snack.label :name %>
            <%= snack.text_field :name %>
            <%= snack.label :calories %>
            <%= snack.number_field :calories %>
            <%= snack.label :deliciousness %>
            <%= snack.select :deliciousness, (1..10) %>
        <% end %>
    <%= f.submit %>
<% end %>



<!-- <h3>Form tag</h3>

<%= form_tag(retailers_path) do %>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
<% end %> -->

22-authorization/snack-tracker/app/views/retailers/show.html.erb
<h2>Name: <%= @retailer.name %></h2>
<h3>Year Established: <%= @retailer.year_established %></h3>
<ul>
    <% @retailer.snacks.each do |snack| %>
        <li><%= link_to snack.name, snack_path(snack) %></li>
    <% end %>
</ul>

22-authorization/snack-tracker/app/views/snacks/_snack_form.html.erb
<%= render partial: "shared/error_list", locals: {new_thing: @snack} %>

<%= form_for @snack do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :calories %>
    <%= f.number_field :calories %>
    <%= f.label :deliciousness %>
    <%= f.select :deliciousness, (1..10) %>
    <%= f.label :retailer %>
    <%= f.collection_select :retailer_id, Retailer.all, :id, :name %>
    <%# object we're making (implied), field to fill in, collection to include,
        value (id), text to display %>
    <%= f.submit "Snackify" %>

<% end %>

22-authorization/snack-tracker/app/views/snacks/edit.html.erb
<h1>Edit this Snack</h1>

<%= render "snack_form" %>

<h3>Delete this snack</h3>

<%= form_tag snack_path, method: "DELETE" do %>
    <%= submit_tag "Destroy this snack" %>
<% end %>

22-authorization/snack-tracker/app/views/snacks/home.html.erb
<h1>This is my super Snack app</h1>

22-authorization/snack-tracker/app/views/snacks/index.html.erb
<h1>Snack Index Page</h1>

<h2>My favorite cookie is <%= cookies["my_favorite"] %></h2>
<h2>My secret favorite cookie is <%= session["secret_favorite"] %></h2>

<h2>The last snack I visited is <%= cookies["last_visited"] %></h2>

<ul>
    <% @snacks.each do |snack| %>
        <li><%= link_to snack.name, snack_path(snack.id) %></li>
    <% end %>
</ul>

22-authorization/snack-tracker/app/views/snacks/new.html.erb
<h1>Create a New Snack</h1>

<%= render "snack_form" %>

22-authorization/snack-tracker/app/views/snacks/show.html.erb
<h1 class="title">Detail Page for <%= @snack.name %></h1>

<div>Calories: <%= @snack.calories %></div>
<div>Deliciousness: <%= @snack.deliciousness %></div>
<div>Made by: <%= link_to @snack.retailer.name, retailer_path(@snack.retailer) %> </div>
<!-- <a href="/snacks">Back to Index Page</a> -->
<%= link_to "Edit this snack", edit_snack_path(@snack) %>
<%= link_to "Home Page", home_path %>
<%= link_to "Snacks Index", snacks_path %>